server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

  #添加文件上传大小限制，覆盖默认的1MB
  servlet:
    multipart:
      # 单个文件最大10MB，满足你页面2M的要求，留足余量
      max-file-size: 10MB
      # 单次请求最大10MB，支持多文件上传
      max-request-size: 10MB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  rustfs:
    endpoint: ${sky.rustfs.endpoint}
    access-key: ${sky.rustfs.access-key}
    secret-key: ${sky.rustfs.secret-key}
    bucket-name: ${sky.rustfs.bucket-name}


